CREATE TABLE IF NOT EXISTS users (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'USER',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 owner_id INTEGER NOT NULL,
 name TEXT NOT NULL,
 tag TEXT,
 logo_url TEXT,
 status TEXT NOT NULL DEFAULT 'PENDING',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS team_members (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 team_id INTEGER NOT NULL,
 game_name TEXT NOT NULL,
 uid TEXT NOT NULL,
 role TEXT DEFAULT 'PLAYER',
 FOREIGN KEY(team_id) REFERENCES teams(id)
 ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tournaments (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 fee INTEGER NOT NULL DEFAULT 0,
 max_teams INTEGER NOT NULL DEFAULT 48,
 status TEXT NOT NULL DEFAULT 'OPEN',
 description TEXT,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS slots (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 tournament_id INTEGER NOT NULL,
 slot_time TEXT NOT NULL,
 group_name TEXT NOT NULL,
 capacity INTEGER NOT NULL DEFAULT 12,
 FOREIGN KEY(tournament_id)
 REFERENCES tournaments(id)
 ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS registrations (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 team_id INTEGER NOT NULL,
 tournament_id INTEGER NOT NULL,
 slot_id INTEGER,
 order_code TEXT UNIQUE NOT NULL,
 amount INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'AWAITING_PAYMENT',
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(team_id) REFERENCES teams(id),
 FOREIGN KEY(tournament_id) REFERENCES tournaments(id),
 FOREIGN KEY(slot_id) REFERENCES slots(id)
);

CREATE TABLE IF NOT EXISTS payments (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 registration_id INTEGER NOT NULL,
 gateway TEXT NOT NULL DEFAULT 'BANK',
 external_id TEXT,
 amount INTEGER NOT NULL,
 status TEXT NOT NULL DEFAULT 'PENDING',
 raw_json TEXT,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(registration_id)
 REFERENCES registrations(id)
);

CREATE TABLE IF NOT EXISTS matches (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 tournament_id INTEGER NOT NULL,
 slot_id INTEGER,
 room_id TEXT,
 room_password TEXT,
 start_at TEXT,
 status TEXT NOT NULL DEFAULT 'SCHEDULED',
 FOREIGN KEY(tournament_id)
 REFERENCES tournaments(id),
 FOREIGN KEY(slot_id)
 REFERENCES slots(id)
);

CREATE TABLE IF NOT EXISTS results (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 match_id INTEGER NOT NULL,
 team_id INTEGER NOT NULL,
 placement INTEGER NOT NULL DEFAULT 0,
 kills INTEGER NOT NULL DEFAULT 0,
 points INTEGER NOT NULL DEFAULT 0,
 FOREIGN KEY(match_id)
 REFERENCES matches(id)
 ON DELETE CASCADE,
 FOREIGN KEY(team_id)
 REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS sessions (
 token TEXT PRIMARY KEY,
 user_id INTEGER NOT NULL,
 expires_at INTEGER NOT NULL,
 FOREIGN KEY(user_id)
 REFERENCES users(id)
 ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER,
 action TEXT NOT NULL,
 target TEXT,
 details TEXT,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_expiry
ON sessions(expires_at);

CREATE INDEX IF NOT EXISTS idx_registrations_team
ON registrations(team_id);

CREATE INDEX IF NOT EXISTS idx_payments_registration
ON payments(registration_id);

CREATE INDEX IF NOT EXISTS idx_teams_owner
ON teams(owner_id);
