name = "custom151"
main = "src/index.js"
compatibility_date = "2026-09-04"

workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "vua-tu-chien-mua1"
database_id = "a767fa8a-7ae9-41ef-acd8-d7d214cb40bd"
migrations_dir = "migrations"

[vars]
SITE_NAME = "GIẢI ĐẤU VUA TỬ CHIẾN – MÙA 1"
